### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Ibrahim-a-Ibrahim** [dss-extensions/OpenDSSDirect.jl#62] opened 2020-10-12 03:37 UTC
I am trying to use the Pmpp parameter for PVsystems. It seems that it is not supported in the last release but it is added on Master. Could you release new version?

Thank you!

**Comment by PMeira** [comment] 2020-10-12 17:51
Ah, sorry, I didn't notice there wasn't a recent release (we probably forgot to tag them). I'm working on it now, more precisely trying to register the new version.

Note that there are a lot of changes from DSS C-API (versions 0.10.5 and 0.10.6) since the last ODD.jl public release. I recommend taking a look at https://github.com/dss-extensions/dss_capi/releases/tag/0.10.6

**Comment by PMeira** [comment] 2020-10-12 18:46
@Ibrahim-a-Ibrahim OpenDSSDirect.jl v0.7.0 released, confirmed by installing it on Julia 1.5.2. 
Closing the ticket, please reopen it if you find any installation issue -- in that case, remember to specify with Julia version and OS.

**Closed by PMeira** 2020-10-12 18:46 UTC
